---
kind: pipeline
type: docker
name: default

steps:
- name: terraform plan
  image: hashicorp/terraform:latest
  access_key:
    from_secret: access_key
  secret_key:
    from_secret: secret_access_key
  commands: 
    - terraform init
    - terraform plan -var-file:"prod.tfvars" -auto-approve

when:
  branch:
  - main