---
kind: pipeline
type: docker
name: default

steps:
- name: terraform plan
  image: hashicorp/terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
        from_secret: access_key
    AWS_SECRET_ACCESS_KEY:
        from_secret: secret_access_key
  commands: 
    - terraform init
    - terraform plan -var-file:"prod.tfvars"

when:
  branch:
  - main